cursor #cad3f5
cursor_text_color #a5adcb

foreground            #cad3f5
background            #24273a
selection_foreground  #24273a
selection_background  #b7bdf8
url_color             #8aadf4

color0   #1e2030
color1   #ff7299
color2   #7af48c
color3   #fff872
color4   #6e96e7
color5   #163470
color6   #8aadf4
color7   #eff4ff
color8   #92969e
color9   #ff9fba
color10  #a5ffb3
color11  #fffaa5
color12  #a0bfff
color13  #b1cbff
color14  #cdddff
color15  #f8faff
